version: "3.8"
services:
  db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practice
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: >
      mysqld
        --character-set-server=utf8
        --collation-server=utf8_unicode_ci
        --skip-character-set-client-handshake
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: unless-stopped